feat: Do not error when the provider closes the connection
n0-computer/sendme-legacy pull request #124
Opened 2023-02-07 15:52 UTC by flub

This makes it so that the provider is allowed to close the connection
after a transfer is completed, without the getter resulting in an
error.

2023-02-07 16:46 UTC, flub commented
Ugh, this is **wrong**.

If the provider closes all the connections this brutally then there is no guarantee that the getter really receives all the data in time.

Guess we really do need graceful termination of the sendme provider.

2023-02-08 11:00 UTC, flub commented
> Ugh, this is **wrong**.
> 
> If the provider closes all the connections this brutally then there is no guarantee that the getter really receives all the data in time.
> 
> Guess we really do need graceful termination of the sendme provider.

Turns out the fix was a lot easier than doing all of graceful termination: https://github.com/n0-computer/sendme/pull/124/commits/3d3e055d7cc02f2d42a4d4793d53eb529d9e6cda

PTAL

2023-02-08 11:04 UTC, flub commented
Ugh, realised that this already changes the protocol to one-request-per-stream because `SendStream::finish` does make it so the provider can no longer send anything.  So this is **still** incomplete: the stream should be closed entirely after handling a single request

2023-02-08 15:47 UTC, flub commented on src/get.rs
> +    drop(writer);
This isn't strictly needed, I'm open to remove it again.  Currently the provider tells the getter to stop already, this is the symmetric part enforcing this explicitly on the getter side.  Not doing this and trying to use the writer for anything other than `finish` after this will already result in a failure even without these two lines.

2023-02-08 15:48 UTC, flub commented on src/get.rs
> +                drop(reader);
This is also optional, it will be dropped implicitly very soon otherwise.  It does also hide a call to `RecvStream::stop` which doesn't matter much in any case but does tell the sender that it can't use the stream anymore.  This matches the protocol.

2023-02-08 15:53 UTC, flub commented on src/protocol.rs
> +pub(crate) enum Closed {
I'm open to bikeshedding this name... It's a bit odd as it also applies to `stop` not just `close`.  But `ErrorCode` seems also odd somehow.

2023-02-08 15:56 UTC, flub commented on src/protocol.rs
> +impl TryFrom<VarInt> for Closed {
The typesystem doesn't tell me when I missed a variant here.  That makes me a little sad.

2023-02-08 15:57 UTC, flub commented on src/provider.rs
> -    loop {
Most of this code is simply dedented because this loop was removed and there's now a single `if let`.

2023-02-08 15:58 UTC, flub commented on src/provider.rs
> +    reader.stop(Closed::RequestReceived.into())?;
This is new, we don't allow the client to still write on this stream after we read the request.  The client has a matching finish call on this.

2023-02-08 16:01 UTC, flub commented on src/provider.rs
> +                writer.finish().await?;
This is new and the source of all my troubles in this PR.  But also the raison d'etre.

We need to be sure the client has really received all the data before emitting the `TransferCompleted`.  Otherwise a user of Provider might call `shutdown` before we have really finished transferring all the data and upon closing the connection data is lost.  That's pretty flaky to track down :grin:

2023-02-08 16:01 UTC, flub commented on src/provider.rs
> +                writer.finish().await?;
This finish is also new, mirror of `TransferCompleted` case.

2023-02-08 16:02 UTC, flub commented
Third time is a charm.  Please review carefully.

2023-02-09 19:18 UTC, ramfox requested changes
Cool, so we are now ensuring that the transfer is finished (all data is read by the `get` side) before notifying the `Event` stream that the transfer has been completed. 🔥 

This is not utilized by our CLI yet, so to "see it in action" you have to run the tests.

I only had one bit I was confused by, and it's in the `Closed` documentation!

2023-02-09 19:18 UTC, ramfox commented on src/protocol.rs
> +/// *stop* sending data.  Both these associate and `error_code` with that operation, closing
I don't understand "Both these associate and `error_code` with that operation". I'm not sure what "both these" and "that" are referring to.

2023-02-09 19:18 UTC, ramfox commented on src/protocol.rs
> +pub(crate) enum Closed {
I don't think the name `Closed` is confusing. I read it as "this is the reason the stream is closed", rather than "this has to do with the action of 'closing' rather than 'stopping' specifically".

2023-02-09 21:00 UTC, dignifiedquire commented on src/get.rs
> +    drop(writer);
seems like good cleanup to have this

2023-02-09 21:02 UTC, dignifiedquire commented on src/get.rs
> +    drop(writer);
Wait actually this seems wrong, we should only close the writer once we have received the full response. While right now we don't sent acks or errors, I would expect a next extension, to actually send a final thing of "all good" or "error: xyz" when the transfer completed.

2023-02-09 21:03 UTC, dignifiedquire commented on src/lib.rs
> +                    Event::TransferCompleted { .. } => {
why didn't wee need the special casing before?

2023-02-09 21:04 UTC, dignifiedquire commented on src/lib.rs
> +                    _ => events.push(event),
should handle abortion as well, otherwise it will hang in a failure case

2023-02-09 21:05 UTC, dignifiedquire commented on src/provider.rs
> +    reader.stop(Closed::RequestReceived.into())?;
as mentionend on the reader side, this should only happen once the transfer is done imo

2023-02-10 08:49 UTC, flub commented on src/get.rs
> +    drop(writer);
I think I'm slightly favour of keeping this in for now, it is how the current protocol works.  If we change the protocol then it's easy enough to change this.

(With the current protocol I don't immediately see any benefit to adding explicit ack or err responses.  There is nothing the server can do about it and it adds an extra roundtrip.  The provider already gets an ack by leveraging QUIC's built-in acks via `.finish()`.)

2023-02-10 08:51 UTC, flub commented on src/provider.rs
> +    reader.stop(Closed::RequestReceived.into())?;
On this side I care a little more with the current protocol.  If we don't a misbehaving client can fill up buffers on our side which is wasteful and can probably be abused for DDOS things etc.

2023-02-10 09:01 UTC, flub commented on src/lib.rs
> +                    Event::TransferCompleted { .. } => {
Before we shut down the provider as soon as the `get` function returned.  If this happened while the provider was suspended in the await of the new `SendStream::finish()` call then that ended up closing the connection (which is still not graceful) which meant the finish call would return in an error (`LocallyClosed`) and the `TransferCompleted` event was never sent.  Further down the test would fail due to the missing `TransferCompleted` event.

2023-02-10 09:04 UTC, flub commented on src/lib.rs
> +                    _ => events.push(event),
I protected that with a timeout on line 260 which is needed even if `TransferAborted` is handled here.  Abortion is not the expected case so I don't think it's worth adding more code to the test here for it, given the timeout already makes the test robust.

Though you could argue that's two bits of code which are far away from each other with too tight coupling.

2023-02-10 09:26 UTC, flub commented on src/protocol.rs
> +/// *stop* sending data.  Both these associate and `error_code` with that operation, closing
`s/and/an/` which made this more confusing than it needed to be.  I've tried to improve the wording.

2023-02-13 14:39 UTC, ramfox approved these changes

2023-02-13 15:34 UTC, merged