feat: transfer multiple files
n0-computer/sendme-legacy pull request #48
Opened 2023-01-24 06:17 UTC by ramfox

closes #36 

### Decisions I made that are up for debate

- The word `ListOfBlobs` was unpleasing to look at and to use for variable names. I changed it to `Collection`, which is a word that can maybe grow with us as `sendme` grows in capabilities. Anyway, can change it back, but I like the name.
- We don't "pre-check" the hashes to see if any are missing before starting a transfer. Trying to get to the actual "transfering" asap.

- As soon as a hash is `NotFound`, we end the transfer. We could continue trying to send other hashes in the list (if there are any).

- In the case of an error, we don't clean up any files that have already been transfered successfully. This seems like a reasonable expectation to me, but open to be disagreed with.

- In the case of an error, we don't report it to the remote, we just close the connection / stop the transfer.

- The `out` flag is now the expected directory you want to save the given file. We use the filename from the original path to name the file. In the case of stdin, this is the hash of the file.
- The `MAX_DATA_SIZE` I have as a limit for the entire `Collection` not individual files in the collection, so the `MAX_DATA_SIZE` is still the
  maximum we are willing to transfer. If this was not the intention lmk!

- The cli "transfering" progress bars are off, since the only information we have in main (in the current set up) is the TOTAL amount of data we are sending with the collection, not the sizes of the individual files. Open for us to pass on more information in the `Event`s but just didn't want to overburden this PR.

- There is currently a separate (mem) database for `Collection` data than the blobs themselves. It seems reasonable to me to instead store the `Collection` in a tempfile, and store them in the same database as the blobs. This would streamline our DB story and also streamline the protocol code a bit.

### General Request
- The buffering story in sendme is pretty hard to follow and debug currently.  
  Also, we probably do too much of it. Happy to take advice on this front!

### CLI usage
```
sendme server first_file second_file third_file
Available Data:
- a2d21fd875303f42cf43c78e778a2e5439407ea26687ba2eb98000ba8d6d85c3: 287264485 bytes
- 07ac3b46a681779978f808c4894f2d59552239203aa962bae91707a6307afdc9: 66659 bytes
- 06ca947e27c8f7ebf1e6ffc395f7f140c66dbb80ca8e05fda79ede8b7a06dba2: 1507262 bytes

collection:
- 3d647c0dd31ef5ae744f00675dd5c30efcee47a96308fed650dffc9256569e7c

Serving from c03094751d5848565ff15c49137ebfa0a98bb49e702ea7d13199dc00a13c688c

```

```
# transfer the whole collection
$ sendme client 06ca947e27c8f7ebf1e6ffc395f7f140c66dbb80ca8e05fda79ede8b7a06dba2 new_out_dir --peer-id c03094751d5848565ff15c49137ebfa0a98bb49e702ea7d13199dc00a13c688c

...

$ ls new_out_dir
first_file
second_file
third_file
```

```
# transfer a single file from the collection
$ sendme client 07ac3b46a681779978f808c4894f2d59552239203aa962bae91707a6307afdc9 new_out_dir --peer-id c03094751d5848565ff15c49137ebfa0a98bb49e702ea7d13199dc00a13c688c

...

$ ls new_out_dir
07ac3b46a681779978f808c4894f2d59552239203aa962bae91707a6307afdc9
```

### Rough protocol walkthrough

Server: waits for a request with a hash
- if the server has the hash in its collection database:
    -  it sends back a `Res::FoundCollection`, with the size of the encoded `Collection` data, the size of the actual amount of data we want to transfer, and the bao outboard data. Then it immediately sends the bao encoded data.
   - it decodes the Collection data, and iterates through each blob in the collection
        - if that blob hash can be found in the blob datasbase, it sends a `Res::Found`, with the size of the raw blob data & the bao outboard data, followed immediately with the bao encoded data
        - if it cannot be found, it sends back `Res::NotFound` and ends the transfer
- if the server has the hash in its blob database:
    - it sends back a `Res::Found`, with the size of the blob raw data, and the bao outboard data
- if the server cannot find the hash:
    -  it sends back `Res::NotFound` and ends the transfer

Client: requests a hash
- it waits for a response
- `Res::FoundCollection`
   - it reads the encoded `Collection` data, decodes it, and parses it into a `Collection`
   - it expects the blobs to come in in the order of the `Collection.blobs` vector field
   - for each blob:
       - it read off a `Res::Found` message, followed by the bao encoded data
       - it decodes the data & writes it to a duplexstream
       - the other end of the duplex stream is yielded in an `Event`, waiting to be read
    - if it gets to a `Res::NotFound` message, it ends the transfer
 - `Res::Found`
       - it read off a `Res::Found` message, followed by the bao encoded data
       - it decodes the data & writes it to a duplexstream
       - the other end of the duplex stream is yielded in an `Event`, waiting to be read
-  `Res::NotFound`
    - it ends the transfer

2023-01-24 16:08 UTC, flub reviewed
Going to re-iterate my high-level comment from discord: I think this protocol is good for a TCP connection and a bit wasted on quic.  Whether we carry on with this to get the UX sorted first is still open of course, I'd be fine with this as first version of the protocol.

2023-01-24 16:08 UTC, flub commented on src/blobs.rs
> +    /// Links to other blobs in this collection
```suggestion
    /// Links to the blobs in this collection
```

2023-01-24 16:08 UTC, flub commented on src/blobs.rs
> +    pub(crate) hash: [u8; 32],
I think we've been using `bao::Hash` directly for hashes.  I don't see why we shouldn't do that?  In any case I'm a big fan of newtypes vs an array of bytes.

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +}
oh, your Debug impl of this is much nicer than mine!

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +        reader.read_buf(&mut buffer).await?;
needs a check for EOF from the reader i think

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +) -> Result<BytesMut> {
consider returing a `Bytes` instead here?  (you can call `BytesMut::freeze`)

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +    if size > buffer.len() {
with the current while loop this should not be possible?

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +    }
It took me ages to realise that was is being read here is exactly the same as what is already in `data`, with the sole purpose of verifying the hash.  I guess this will be nicer once we can have an async bao decoder.  In the mean time maybe add a comment saying "verifying the hash of `data`" or so?

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +        let read = decoder.read(&mut buf)?;
What does the boa error message look like?  It might be worth adding a `.context("hash of Collection data does not match")?` or so

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +    let data = read_data(size, reader, buffer).await?;
do i understand correctly that this reads the entire blob into memory?  we should probably leave a comment so that this is easy to find in the future if so.

2023-01-24 16:08 UTC, flub commented on src/client.rs
> +            // TODO: avoid blocking
where does this block right now?

2023-01-24 16:08 UTC, flub commented on src/main.rs
> +                            tokio::fs::create_dir_all(outpath).await?;
probably want a `.context()` on this with a nice message

2023-01-24 16:08 UTC, flub commented on src/server.rs
> +// than representing true blob data.
The database is in memory only: why not store: `enum BlobOrCollection { Blob(Data), Collection(Collection) }`?  (ok, need better naming)

2023-01-25 04:36 UTC, ramfox commented on src/blobs.rs
> +    pub(crate) hash: [u8; 32],
ahh yes thank you, I was being lazy about implementing `serde`

2023-01-25 04:37 UTC, ramfox commented on src/client.rs
> +}
😊

2023-01-25 04:41 UTC, ramfox commented on src/client.rs
> +    if size > buffer.len() {
This is testing if buffer was already filled with content larger than we expected before this method was called. It feels silly, but can technically happen. I learned the hard way that we may already have the content already in the buffer, I learned the hard way (by passing in a new buffer, rather than reading off the old one). I find all the buffer expectations pretty confusing.

We might want to just split the buffer off to the expected size and continue anyway, rather than testing if we received the right amount of data.

TBH not sure the "right" way forward here.

2023-01-25 04:50 UTC, ramfox commented on src/client.rs
> +            // TODO: avoid blocking
this is just a "left over" comment that really translates to "add async decode to bao"

changing the comment

2023-01-25 05:05 UTC, ramfox commented on src/client.rs
> +        reader.read_buf(&mut buffer).await?;
Okay, yes thank you I meant to bring this up.

I'm a bit confused about what we want here.

The docs for async `read_buf` say, when we read 0 bytes off the reader: "This reader has reached its "end of file" and will likely no longer be able to produce bytes. Note that this does not mean that the reader will always no longer be able to produce bytes."

So is this saying that, for instance, if we have a not-so-fast connection, we may have 0 bytes to read off the stream, but may have more in the future? Or is it safe to assume that when we read 0 bytes, we are likely at EOF, and I'm being paranoid?

2023-01-25 05:06 UTC, ramfox commented on src/client.rs
> +        reader.read_buf(&mut buffer).await?;
This "likely" word is tripping me up about expectations.

2023-01-25 05:48 UTC, ramfox commented on src/server.rs
> +// than representing true blob data.
lol too bad I basically used your naming

2023-01-25 10:16 UTC, dignifiedquire commented on src/blobs.rs
> +            hash: bao::Hash::from(d.hash),
can you file an issue with `bao` to add optional `serde` support?

2023-01-25 10:23 UTC, dignifiedquire commented on src/get.rs
>                          Res::Found { size, outboard } => {
We should get rid of this event, and always use the collection, to make the construction simpler

2023-01-25 10:34 UTC, rklaehn commented
Tried this out with the test directories from back when I implemented the HAMT. But nothing works because of some limits.

```
# a very large dir with tiny files
cargo run --release provide ../testdir_many_files/hamt1/*
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
...
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
Error: The serialize buffer is full

# a moderately large dir with tiny files
cargo run --release provide ../testdir_many_files/nohamt1/*
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
...
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
Error: The serialize buffer is full

# a dir with a few large files - fails when requesting:
Fetching: a4eae4b9cfd5d62076af83d07c0cf784133ebb2f3975fd2ea93ee8f04943e56c
[1/3] Connecting ...
[2/3] Requesting ...
Error: size too large: 5000000000 > 1073741824
```

Maybe we should increase the limits a bit...

2023-01-25 10:39 UTC, flub commented on src/provider.rs
> +    let mut blobs = Vec::new();
You can call `Vec::with_capacity` (and for the HashMap above) using the length of `data_sources`

2023-01-25 10:39 UTC, flub commented on src/provider.rs
> +async fn send_blob<W: AsyncWrite + Unpin>(
this code should probably be merged with the blob branch in the loop of `handle_stream()` above.  a bit too repetitive.

2023-01-25 10:39 UTC, flub commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
I tried not to nitpick on this, but I find it really hard to read.  I never know what that raw size applies to.  Can we name this `total_blobs_size` instead?  I don't mind being verbose.

2023-01-25 10:39 UTC, flub commented on src/blobs.rs
> +struct SerdeBlob {
I haven't tried this, but can this struct not be avoided by using `#[serde(serialize_with = "serialize_bao_hash")]` on the `Blob::hash` field?  You'd have to write `serialize_bao_hash` of course.

2023-01-25 10:39 UTC, flub commented on src/protocol.rs
> +        raw_transfer_size: usize,
Just like in the `Collection` itself this name  keeps confusing me to no end, `total_blobs_size` would help me I think.

2023-01-25 10:44 UTC, rklaehn commented
So it seems that around 1000 files is the current limit for the number of files.

I tried it out with 1000 empty files, and am getting this:

send side seems to work:
```
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
...
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes

collection:
- 7ebc5acba68de920573dd4194ad661ce1858ff9ee546ebc91de9bc1924eea4ee
PeerID: e4e0e99e0efb496b0534a456eb6783153e5c7bd515aa44d196b3b210b15ef9da
```

but recv side:
```
❯ cargo run --release -- get --peer-id e4e0e99e0efb496b0534a456eb6783153e5c7bd515aa44d196b3b210b15ef9da 7ebc5acba68de920573dd4194ad661ce1858ff9ee546ebc91de9bc1924eea4ee > /dev/null
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/sendme get --peer-id e4e0e99e0efb496b0534a456eb6783153e5c7bd515aa44d196b3b210b15ef9da 7ebc5acba68de920573dd4194ad661ce1858ff9ee546ebc91de9bc1924eea4ee`
Error: no more data available
```

2023-01-25 11:04 UTC, rklaehn commented on src/blobs.rs
> +            hash: bao::Hash::from(d.hash),
bao::Hash is just a reexport of blake3::Hash.

https://github.com/oconnor663/bao/blob/master/src/lib.rs#L46

So you would have to file this issue in blake3 directly. I did it here: https://github.com/BLAKE3-team/BLAKE3/issues/290

2023-01-25 11:30 UTC, rklaehn commented on src/blobs.rs
> +struct SerdeBlob {
There is also `#[serde(with = ...)` which allows you to define a module. Worth a try, but the current way is also perfectly fine imho.

2023-01-25 11:31 UTC, dignifiedquire commented on src/lib.rs
> +    // TODO: random ports? rather than assigning?
yes: https://github.com/n0-computer/sendme/issues/49

2023-01-25 11:32 UTC, dignifiedquire commented on src/lib.rs
> +    async fn single_file(filename: &str, data: &[u8], wrapped: bool, port: u16) -> Result<()> {
In line with the above, I would like to see the `wrapped` option be removed, and have all files be always transferred as part of a collection

2023-01-25 11:33 UTC, dignifiedquire commented on src/lib.rs
> +        let mut i = 0;
is this used for anything?

2023-01-25 11:35 UTC, dignifiedquire commented on src/provider.rs
> +// Creates a database of blobs (stored in outboard storage) and Collections, stored in memory.
tripple slash for doc comments

2023-01-25 11:40 UTC, dignifiedquire commented on src/provider.rs
> +    // NOTE: we can't use the postcard::MaxSize to estimate the encoding buffer size
wrote a comment regarding this issue: https://github.com/jamesmunns/postcard/issues/46#issuecomment-1403477151

2023-01-25 11:40 UTC, dignifiedquire commented
My main high level issue is that I want the individual file transfer to be removed, in favor of always sending a collection. The overhead should be minimal, and it makes the code a lot simpler.

2023-01-25 11:41 UTC, dignifiedquire commented
(sorry did not mean to close this)

2023-01-25 11:49 UTC, rklaehn requested changes
See the comments I added when trying this out.

The low limits is an inconvenience, but the error I think is a genuine bug. See https://github.com/n0-computer/sendme/pull/48#issuecomment-1403414821

2023-01-25 12:01 UTC, flub commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
We should not send `usize` over to different machines.  Probably should be `u64`.

2023-01-25 12:17 UTC, rklaehn commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
usize would also be a bit too small. It is plausible that you may want to send more than 4gb on a 32 bit machine.

2023-01-25 13:49 UTC, flub commented on src/get.rs
>                          Res::Found { size, outboard } => {
The implication is that the hash for a blob can no longer verify the fetching of the collection.  So you need to fetch the collection (which should admittedly be small) without verifying.  However when you do have a collection you probably do want to verify it as it might be a huge thing.  So what tradeoff do we want to make here?  Fetch the collection without verifying as long as it is smaller than some size?

2023-01-25 16:45 UTC, ramfox commented on src/client.rs
> +        reader.read_buf(&mut buffer).await?;
fixed by https://github.com/n0-computer/sendme/pull/51

2023-01-25 19:55 UTC, ramfox commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
Nitpick away! I feel naming for clarity is super important and am happy to have feedback on it.

2023-01-25 20:15 UTC, ramfox commented on src/blobs.rs
> +struct SerdeBlob {
ya, I was intimidated by doing `#[serde(with = ...)` because the `serde` docs for `Deserialize` describe having to also implement a `Vistitor`, which seemed needlessly complicated for translating a 32 byte array to a hash.  So I went for path of least resistance & used a `container-attr` rather than the `field-attr`.

But! I found a working example where someone described how you don't have to impl `Visitor` to get `Deserialize` to work: https://users.rust-lang.org/t/need-help-with-serde-deserialize-with/18374/5

So, using `#[serde(with = ...)` now!

2023-01-26 00:31 UTC, ramfox commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
What do I do when we have to do things like 
`buffer.split_to(usize)` when we have to "downcast" to `usize` anyway?

2023-01-26 01:57 UTC, ramfox commented on src/blobs.rs
> +struct SerdeBlob {
actually, the example without using a `Visitor` didn't work properly, just implemented it w/ a `Visitor` and works as expected now.

2023-01-26 03:26 UTC, ramfox commented on src/get.rs
>                          Res::Found { size, outboard } => {
We currently use `Res::Found` to deliver the `outboard` encoded data & to ensure that we don't receive a `Re::NotFound` message instead. It's easy enough to error if we get a `Res::Found` for the first response, and leave `Res::Found` as a valid response when we are waiting for the blob data.

Which is how I have it set up in the latest commit.

If we really want to remove the `Res::Found` message, perhaps the protocol is changed to this:
- Receive `FoundCollection`
- verify FoundCollection, expect blobs in the order in which they are listed in the `Collection`
- receive length prefixed bao `outboard` encoded data
- receive length prefixed actual content
- verify content using outboard encoding & hash (that we have from the `Collection`)

My main question is what do we do in the case where the `Provider` does not have the content of a blob? Does it still send `Res::NotFound`, even though we will not be expecting a `Res` message on the `get` side? Or does it just close the connection, and the `getter` just reports an error, rather than a specific `NotFound` message?

2023-01-26 06:58 UTC, rklaehn commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
If you have to load the entire data into memory, your data can not be larger than `usize`. But you don't have to do that.

What you have to do if you e.g. want to handle a 1TB file on a 32bit / 4GB max architecture is to make sure that you never load more than 4GB in memory. But the overall file can still be larger than 4GB.

E.g. the std::io and tokio::io methods that deal with files are all working with u64. See for example https://doc.rust-lang.org/std/fs/fn.copy.html . It uses an internal buffer that is (much) less than 4GB, but the overall amount being can be much more than 4GB.

When writing code on 32 bit that deals with large files you have to constantly think about whether a certain 64 bit number is safe to downcast to usize or not.

2023-01-26 07:28 UTC, dignifiedquire commented on src/get.rs
>                          Res::Found { size, outboard } => {
the protocol you described is what I was expecting, yes. 
I would abort if a blob is not found for now, given that the original collection found should only be sent if the provider has the whole collection

2023-01-26 07:50 UTC, dignifiedquire commented on src/get.rs
> +                            yield Event::Requested { size: total_blobs_size };
should probably extend this with the notion that this is a collection not a blob

2023-01-26 07:51 UTC, dignifiedquire commented on src/get.rs
> +                            let collection = Collection::decode_from(data, outboard, hash).await?;
what about `yield`ing the details of the collection (e.g. it's name and number of blobs)? maybe add an event `Event::ReceivedCollection(Collection)`?

2023-01-26 07:53 UTC, dignifiedquire commented on src/get.rs
> +    println!("decoding theses bytes: {:?}", data);
remove

2023-01-26 07:58 UTC, dignifiedquire commented on src/get.rs
>                          Res::Found { size, outboard } => {
yeah after reviewing the latest state, I think you can leave the protocol as is, it's pretty clean now, thanks

2023-01-26 10:44 UTC, rklaehn commented
I still see a bug when trying to sync a directory containing 30 empty files:

provide side works:
```
❯ cargo run --release -- provide ../testdir_many_files/nohamt3/*
   Compiling zeroize v1.5.7
   Compiling base64ct v1.5.3
   Compiling signature v1.6.4
   Compiling sha2 v0.10.6
   Compiling ed25519 v1.5.2
   Compiling der v0.6.1
   Compiling curve25519-dalek v3.2.0
   Compiling s2n-quic-crypto v0.15.0
   Compiling s2n-quic-platform v0.15.0
   Compiling pem-rfc7468 v0.6.0
   Compiling s2n-quic-rustls v0.15.0
   Compiling ssh-encoding v0.1.0
   Compiling ed25519-dalek v1.0.1
   Compiling s2n-quic v1.14.0
   Compiling spki v0.6.0
   Compiling pkcs8 v0.9.0
   Compiling sec1 v0.3.0
   Compiling ssh-key v0.5.1
   Compiling sendme v0.1.0 (/Users/rklaehn/projects_git/sendme)
    Finished release [optimized] target(s) in 14.61s
     Running `target/release/sendme provide ../testdir_many_files/nohamt3/file_0001 ../testdir_many_files/nohamt3/file_0002 ../testdir_many_files/nohamt3/file_0003 ../testdir_many_files/nohamt3/file_0004 ../testdir_many_files/nohamt3/file_0005 ../testdir_many_files/nohamt3/file_0006 ../testdir_many_files/nohamt3/file_0007 ../testdir_many_files/nohamt3/file_0008 ../testdir_many_files/nohamt3/file_0009 ../testdir_many_files/nohamt3/file_0010 ../testdir_many_files/nohamt3/file_0011 ../testdir_many_files/nohamt3/file_0012 ../testdir_many_files/nohamt3/file_0013 ../testdir_many_files/nohamt3/file_0014 ../testdir_many_files/nohamt3/file_0015 ../testdir_many_files/nohamt3/file_0016 ../testdir_many_files/nohamt3/file_0017 ../testdir_many_files/nohamt3/file_0018 ../testdir_many_files/nohamt3/file_0019 ../testdir_many_files/nohamt3/file_0020 ../testdir_many_files/nohamt3/file_0021 ../testdir_many_files/nohamt3/file_0022 ../testdir_many_files/nohamt3/file_0023 ../testdir_many_files/nohamt3/file_0024 ../testdir_many_files/nohamt3/file_0025 ../testdir_many_files/nohamt3/file_0026 ../testdir_many_files/nohamt3/file_0027 ../testdir_many_files/nohamt3/file_0028 ../testdir_many_files/nohamt3/file_0029 ../testdir_many_files/nohamt3/file_0030`
Available Data:
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
- af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262: 0 bytes
before Collection {
    name: "collection",
    blobs: [
        Blob {
            name: "file_0001",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0002",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0003",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0004",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0005",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0006",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0007",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0008",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0009",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0010",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0011",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0012",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0013",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0014",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0015",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0016",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0017",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0018",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0019",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            ),
        },
        Blob {
            name: "file_0020",
            hash: Hash(
                "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f326 [...]

2023-01-26 13:45 UTC, flub commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
To add to this, while right now we do horrible things like `buffer.split_to(entire_file_size)` we won't be doing this for too long I hope.

2023-01-26 14:47 UTC, flub commented on src/blobs.rs
> +                formatter.write_str("an array of bytes containing hash data")
```suggestion
                formatter.write_str("an array of 32 bytes containing hash data")
```

2023-01-26 14:47 UTC, flub commented on src/blobs.rs
> +    pub async fn decode_from(data: Bytes, outboard: &[u8], hash: bao::Hash) -> Result<Self> {
love this as an associated function :green_heart:

2023-01-26 14:47 UTC, flub commented on src/get.rs
> +// Returns an `AsyncRead` and a `JoinHandle`.
`///`

2023-01-26 15:41 UTC, ramfox commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
Okay cool. For now, is the current set up reasonable, since we will most _not_ be reading the entire file to the buffer for much longer?

2023-01-26 15:44 UTC, ramfox commented on src/get.rs
> +// Returns an `AsyncRead` and a `JoinHandle`.
one day I'll remember this... :)

2023-01-26 15:53 UTC, ramfox commented on src/get.rs
>                          Res::Found { size, outboard } => {
> I would abort if a blob is not found for now, given that the original collection found should only be sent if the provider has the whole collection

We currently do not check if each member of the collection exists at the provider before sending over the `FoundCollection` response. Should we refactor to do that, or is this case covered sufficiently in your mind now that we are keeping the `Res::Found` response?

2023-01-26 16:04 UTC, dignifiedquire commented on src/get.rs
>                          Res::Found { size, outboard } => {
at least a todo that we should check at the beginning

2023-01-26 16:35 UTC, ramfox commented on src/blobs.rs
> +    pub(crate) raw_size: usize,
The conclusion made (in discord discussion) is to fix any issues in a follow-up, as rklaehn's upcoming planned work will likely eliminate many places where we currently have issues.

2023-01-26 18:49 UTC, ramfox commented
> I still see a bug when trying to sync a directory containing 30 empty files:
> 
> provide side works:
> 
> ```
> ❯ cargo run --release -- provide ../testdir_many_files/nohamt3/*
>    Compiling zeroize v1.5.7
> ...
>    
> collection:
> - cbf64610540529cf9f8ad4fd217fd6b8bf08421c6a230ff4c17c0b367b613b3c
> PeerID: 321d91031dcd74227f16dd9c3574b146eedf44f24735eeb33723fb3036de35e1
> Auth token: 49f398fabebe087e53f897e24928d131fd5b2f77e59fe521f112c0f3b5fb0e0f
> ```
> 
> but get side bails out:
> 
> ```
> sendme on  ramfox/blobs is 📦 v0.1.0 via 🦀 v1.66.0 
> ❯ cargo run --release -- get --peer-id 321d91031dcd74227f16dd9c3574b146eedf44f24735eeb33723fb3036de35e1 49f398fabebe087e53f897e24928d131fd5b2f77e59fe521f112c0f3b5fb0e0f cbf64610540529cf9f8ad4fd217fd6b8bf08421c6a230ff4c17c0b367b613b3c
>     Finished release [optimized] target(s) in 0.11s
>      Running `target/release/sendme get --peer-id 321d91031dcd74227f16dd9c3574b146eedf44f24735eeb33723fb3036de35e1 49f398fabebe087e53f897e24928d131fd5b2f77e59fe521f112c0f3b5fb0e0f cbf64610540529cf9f8ad4fd217fd6b8bf08421c6a230ff4c17c0b367b613b3c`
> Fetching: cbf64610540529cf9f8ad4fd217fd6b8bf08421c6a230ff4c17c0b367b613b3c
> [1/3] Connecting ...
> [2/3] Requesting ...
> Error: no more data available
> ```

This bug occurs because we don't have the "right" estimate for encoding overhead in postcard, when we `write_response` in `src/provider.rs`

However, it occurs to me that we probably shouldn't be sending the boa encoded data (the culprit for ballooning the postcard encoding overhead) in our response messages anyway, and should probably adjust the protocol regardless of how we better estimate the postcard overhead in our buffer.

2023-01-26 21:25 UTC, dignifiedquire commented on src/blobs.rs
> +    pub fn name(&self) -> String {
should return `&str`

2023-01-26 21:27 UTC, dignifiedquire approved these changes
one last nit, otherwise lgtm

2023-01-27 09:47 UTC, merged